# Generated by Django 2.0 on 2017-12-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votelog',
            old_name='VoteLog_id',
            new_name='votelog_id',
        ),
    ]
